name: Update Submodules

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Update submodules to latest
        run: |
          echo "Current submodule status:"
          git submodule status
          
          echo "Updating submodules..."
          git submodule update --remote --merge
          
          echo "New submodule status:"
          git submodule status
      
      - name: Check for changes
        id: changes
        run: |
          if git diff --staged --quiet && git diff --quiet; then
            echo "No changes detected"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "Auto-update submodules to latest versions
          
          🤖 Generated with GitHub Actions
          
          Updated submodules:
          - network: $(cd network && git log --oneline -1)
          - webpage: $(cd webpage && git log --oneline -1)"
          
          git push
      
      - name: Summary
        run: |
          if [ "${{ steps.changes.outputs.changes }}" == "true" ]; then
            echo "✅ Submodules updated and pushed"
          else
            echo "ℹ️ No updates needed - submodules are already current"
          fi